---
# tasks file for audit
- name: include os-specific variables
  include_vars: "{{ansible_os_family}}.yml"

- include: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- include: setup-debian.yml
  when: ansible_os_family == "Debian" 

- name: deploy auditd.conf
  template: >
      src=auditd.conf.j2
      dest=/etc/audit/auditd.conf
      backup=yes
  notify: restart auditd

- include: dispatch-redhat.yml
  when: ansible_os_family == "RedHat"

- include: dispatch-debian.yml
  when: ansible_os_family == "Debian"

- name: deploy audit.rules
  copy: >
      src=rules.{{ansible_architecture}}.{{audit_rules}}.j2
      dest=/etc/audit/rules.d/audit.rules
      backup=yes
  notify: restart auditd
